name: "brew test-bot"

on:
  pull_request:
    paths:
    - Formula/**/*

jobs:
  test-bot:
    runs-on: ${{ matrix.os }}

    if: ${{ !github.event.pull_request.draft }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-24.04
        - macos-15

    steps:
    - name: "Set up Homebrew"
      id: set-up-homebrew
      # Cannot pin by digest: Homebrew/actions uses branch-based versioning
      uses: Homebrew/actions/setup-homebrew@9d95677ac22eae39bdeb2ac8a196adb20a3cedbc # master

    - name: "Cache Homebrew Bundler RubyGems"
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ matrix.os }}-rubygems-

    - run: brew test-bot --only-cleanup-before

    - run: brew test-bot --only-setup

    - run: brew test-bot --only-tap-syntax

    - if: github.event_name == 'pull_request'
      run: brew test-bot --only-formulae --root-url='https://ghcr.io/v2/smykla-labs/af'

    - name: "Upload bottles as artifact"
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: bottles_${{ matrix.os }}
        path: '*.bottle.*'
